version: '3'

services:
  payload:
    #image: node:18-alpine 
    build: .
    ports:
      - '3000'
    environment:
      - PAYLOAD_SECRET=${PAYLOAD_SECRET}
      - DATABASE_URI=mongodb://mongo:27017/nianiba-payload
      # - NODE_ENV=production
    # volumes:
      #- .:/home/node/app
      # - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    # command: sh -c "yarn install --production=false && yarn dev"
    # env_file:
      # - .env
   # healthcheck:
   #   test: ["CMD", "wget", "-q", "--spider", "http://localhost:55658/admin"]
    #  interval: 5s
     # timeout: 20s
      #retries: 10
    depends_on:
      - mongo
        #condition: service_healthy

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    # logging:
      # driver: none
   # healthcheck:
    #  test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
     # interval: 10s
      #timeout: 10s
      #retries: 6
      #start_period: 40s  

volumes:
  data:
 # node_modules: